### ISSUE TITLE
Generator  &  Discriminator 

### ISSUE THREAD

**Issue by jiyonghe** [adityagupta1089/Captcha-Generator-using-cGANs#1]
cgan's have two network, one is Generator Network,another is Discriminator Network,In your model, which are the two networks?

**Comment by adityagupta1089** [comment]
This is an earlier version when we only had a solver for solving the CAPTCHA image to text, the GAN model is not in the latest commit.

**Comment by jiyonghe** [comment]
> 
> 
> This is an earlier version when we only had a solver for solving the CAPTCHA image to text, the GAN model is not in the latest commit.

many many thanks,can you share your GAN model?

**Comment by adityagupta1089** [comment]
I made that but received no significant results (random blur of black color) so I and one of my colleague ended up using a network that takes noise and a library generated CAPTCHA and makes it harder.
